name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Ubuntu Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Install LLVM and Clang"
      uses: KyleMayes/install-llvm-action@v1
      with:
      version: "10.0"
      - uses: actions/checkout@v3
      - name: CMake Configure
        run: cmake .
      - name: Build
        run: make
