name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install_llvm:
    runs-on: ubuntu-latest
    steps:
      - name: "Install LLVM and Clang"
        uses: KyleMayes/install-llvm-action@v1.7.0
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

  build:
    name: "Ubuntu Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: cmake .
      - name: Build
        run: make
