name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Ubuntu Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LLVM
        run: sudo apt remove llvm \
             sudo apt install llvm-15
          
      - name: CMake Configure
        run: cmake .
      - name: Build
        run: make -j8
      - name: Test
        run: ./test.sh
      - name: Test Result
        run: cat ./Testing/Temporary/LastTest.log
