name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Ubuntu Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CMake Configure
        run: cmake .
      - name: Build
        run: make
      - name: Test
        run: ./test.sh

  #test:
  #needs: build
  #runs-on: ubuntu-latest
  #steps:
  #- run: |
  #ls -la
  #cd /home/runner/work/XSharp/XSharp
  #ls -la
  #- uses: actions/checkout@v3
  #- name: GTest
  #working-directory: ${{github.workspace}}
  #run: ./test.sh
