name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Ubuntu Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: CMake Configure
        run: cmake .
      - name: Build
        run: make
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: /home/runner/work/XSharp/XSharp/test.sh
